%{
  #ifdef SERVER
	#define SERVER_INIT
	void cis_initialize(void) {
	  int ret = 0;
	  ret |= solp_init(SOLDRV_PROXY_A, 1, "gsv channel 1 Inject\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 2, "gsv channel 1 Load\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 3, "flow main channel 1 95\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 4, "flow main channel 1 70\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 5, "flow main channel 1 43\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 6, "flow main channel 1 43\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 7, "flow main channel 1 100\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 8, "flow main channel 1 75\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 9, "flow main channel 1 75\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 10, "flow main channel 1 70\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 11, "flow main channel 1 30\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 12, "flow backflush channel 1 10\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 13, "flow backflush channel 1 40\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 14, "flow backflush channel 1 45\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 15, "flow backflush channel 1 30\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 16, "flow backflush channel 1 10\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 17, "flow backflush channel 1 85\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 18, "flow backflush channel 1 5\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 19, "flow backflush channel 1 5\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 20, "flow backflush channel 1 20\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 21, "Press backflush channel 1 Setpoint 25\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 22, "Press backflush channel 1 Setpoint 65\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 23, "Press backflush channel 1 Setpoint 90\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 24, "Press backflush channel 1 Setpoint 60\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 25, "Press backflush channel 1 Setpoint 65\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 26, "Press backflush channel 1 Setpoint 65\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 27, "Press backflush channel 1 Setpoint 60\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 28, "gsv channel 2 Inject\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 29, "gsv channel 2 Load\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 30, "flow main channel 2 82\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 31, "flow main channel 2 70\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 32, "flow main channel 2 78\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 33, "flow main channel 2 78\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 34, "flow main channel 2 30\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 35, "flow main channel 2 30\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 36, "flow backflush channel 2 20\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 37, "flow backflush channel 2 100\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 38, "flow backflush channel 2 90\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 39, "flow backflush channel 2 70\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 40, "flow backflush channel 2 50\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 41, "flow backflush channel 2 20\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 42, "Press backflush channel 2 Setpoint 25\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 43, "Press backflush channel 2 Setpoint 65\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 44, "Press backflush channel 2 Setpoint 68\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 45, "Press backflush channel 2 Setpoint 65\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 46, "Press backflush channel 2 Setpoint 65\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 47, "Press backflush channel 2 Setpoint 65\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 48, "gsv channel 3 Inject\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 49, "gsv channel 3 Load\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 50, "flow main channel 3 70\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 51, "flow main channel 3 45\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 52, "flow main channel 3 45\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 53, "flow main channel 3 40\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 54, "flow main channel 3 30\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 55, "flow main channel 3 30\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 56, "flow backflush channel 3 10\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 57, "flow backflush channel 3 40\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 58, "flow backflush channel 3 40\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 59, "flow backflush channel 3 10\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 60, "flow backflush channel 3 30\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 61, "flow backflush channel 3 20\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 62, "elec bias 1 100\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 63, "elec bias NULL\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 64, "elec bias 2 10\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 65, "elec bias NULL\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 66, "elec bias 3 80\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 67, "elec bias 3 10\n");
	  ret |= solp_init(SOLDRV_PROXY_A, 68, "elec bias NULL\n");
	  if (ret) exit(1);
	}
	void cis_terminate(void) {
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 1);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 2);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 3);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 4);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 5);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 6);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 7);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 8);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 9);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 10);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 11);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 12);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 13);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 14);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 15);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 16);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 17);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 18);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 19);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 20);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 21);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 22);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 23);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 24);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 25);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 26);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 27);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 28);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 29);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 30);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 31);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 32);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 33);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 34);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 35);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 36);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 37);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 38);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 39);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 40);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 41);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 42);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 43);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 44);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 45);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 46);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 47);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 48);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 49);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 50);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 51);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 52);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 53);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 54);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 55);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 56);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 57);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 58);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 59);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 60);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 61);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 62);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 63);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 64);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 65);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 66);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 67);
	  Soldrv_reset_proxy(SOLDRV_PROXY_A, 68);
	}
  #endif
%}
