#! /bin/sh
#__USAGE
#%C
#	Starts Instrument operation, including
#	  batchfile interact
#	  display uavdisp
#	  algorithm labalgo
#	  client uavclt
#	  command log
#	  rtg
#%C	stop
#	Terminates Instrument Operations
#%C	not
#	Prevents Instrument Operation on power up by invoking
#	pick_file /dev/null
#%C	wait
#	Delays starting GSE until flight node has begun
#	the startup process. This verifies that the flight
#	system operates in flight configuration.

#----------------------------------------------------------------
# Perform Common Initializations
#----------------------------------------------------------------
boilerplate=mkdoit2.sh
for dir in /usr/local/lib/src /usr/local/bin /usr/lib; do
  if [ -f $dir/$boilerplate ]; then
	boilerplate=$dir/$boilerplate
	break
  fi
done
[ ! -f $boilerplate ] && {
  echo Cannot locate boilerplate script $boilerplate >&2
  exit 1
}
LocalRing=""
. $boilerplate

#----------------------------------------------------------------
# Allocate Screens
#----------------------------------------------------------------
typeset _scr1 _scr2 _scr3
if [ -n "$_scrdefs" ]; then
  eval `getcon $condev _scr1 _scr2 _scr3`
elif [ $winrunning = yes ]; then
  exec on -t $condev $0 -W $*
else
  eval `getcon $condev _scr2 _scr3`
  _scr1=$_scr0
fi
[ -z "$_scr3" ] && nl_error Unable to allocate enough screens
[ $winrunning = yes ] && {
  winsetsize $_scr0 8 45 `basename $0`
  echo Allocating Screens > $_scr0
  winsetsize $_scr1 30 79 main
  echo "\033/2t \r\c" > $_scr1
  winsetsize $_scr2 11 55 h2o
  echo "\033/2t \r\c" > $_scr2
  escq="\033\""
  logf="$Experiment.log\""
  echo "${escq}t$logf${escq}i$logf${escq}p$logf\033/2t \r\c" >$_scr3
}
typeset _bg_pids='-p'

#----------------------------------------------------------------
# Instrument Startup Sequence
#----------------------------------------------------------------
if [ -n "$wait_for_node" ]; then
  echo Waiting for Flight Node to Boot
  [ $winrunning = yes ] && echo "\033/5t\c"
  namewait -n0 dg
fi
echo Waiting for pick_file
[ $winrunning = yes ] && echo "\033/5t\c"
FlightNode=`pick_file -n interact 2> $_scr0`
[ -n "$FlightNode" ] || nl_error pick_file returned an error

_msgopts="-v -c$FlightNode"
_dcopts="-b$FlightNode -i1"
_cmdopts="-C$FlightNode"

#----------------------------------------------------------------
# Startup Memo Log Window
#----------------------------------------------------------------
on -t $_scr3 less +F //$FlightNode$HomeDir/$Experiment.log
[ $winrunning = yes ] && echo "\033/1t\c" > $_scr3
getcon -r $_scr3
start_rtg /home/uav/flight/uav.rtg

typeset _cfgfile
if [ -z "$MONOCHROME" ]; then
  _attrs=02,06,04,05
  _cfgfile=normal.cfg
fi

echo Waiting for Data Buffer
[ $winrunning = yes ] && echo "\033/5t\c"
namewait -n$FlightNode db

echo Waiting for Command Interpreter
[ $winrunning = yes ] && echo "\033/5t\c"
namewait -n$FlightNode cmdinterp


#----------------------------------------------------------------
# Display Programs:
#----------------------------------------------------------------
scrpaint $_msgopts main $_cfgfile > $_scr1 < $_scr1; stty +opost < $_scr1
[ $winrunning = yes ] && echo "\033/1t\c" > $_scr1
scrpaint $_msgopts h2o $_cfgfile > $_scr2 < $_scr2; stty +opost < $_scr2
[ $winrunning = yes ] && echo "\033/1t\c" > $_scr2
uavdisp $_msgopts $_dcopts -A $_scr1 -a $_scr2 &
_bg_pids="$_bg_pids $!"
[ $winrunning = yes ] && echo "\033/2t\c"

#----------------------------------------------------------------
# Algorithms:
#----------------------------------------------------------------
labalgo $_msgopts $_dcopts $_cmdopts -l &
_bg_pids="$_bg_pids $!"

#----------------------------------------------------------------
# Keyboard Client:
#----------------------------------------------------------------
uavclt $_msgopts $_cmdopts -A $_scr1 -a $_scr2
slay -t /${_scr3#//*/} less
if [ $winrunning = yes ]; then
  _scrs=""
  echo "\033/1t\033/5tShutting Down..."
else
  _scrs=" $_scr0 $_scr1 $_scr2 $_scr3"
fi
exec parent -qvnt3 "$_bg_pids" $_scrs
